/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormErrors: typeof import('./../src/components/form/errors.vue')['default']
    FormSave: typeof import('./../src/components/form/save.vue')['default']
    FormSmall: typeof import('./../src/components/form/small.vue')['default']
    GameCreate: typeof import('./../src/components/game/create/index.vue')['default']
    GameCreateExe: typeof import('./../src/components/game/create/exe.vue')['default']
    GameCreateExeList: typeof import('../src/components/game/create/select-directory.vue')['default']
    GameCreateName: typeof import('./../src/components/game/create/name.vue')['default']
    GameCreateSelectDirectory: typeof import('./../src/components/game/create/select-directory.vue')['default']
    GameItem: typeof import('./../src/components/game/item.vue')['default']
    PageHeader: typeof import('./../src/components/page/header.vue')['default']
    PageName: typeof import('./../src/components/page/name.vue')['default']
    PluginCreate: typeof import('./../src/components/plugin/create/index.vue')['default']
    PluginCreateGameList: typeof import('./../src/components/plugin/create/game-list.vue')['default']
    PluginCreateGithub: typeof import('./../src/components/plugin/create/github.vue')['default']
    PluginCreateSmall: typeof import('./../src/components/plugin/create/small.vue')['default']
    PluginItem: typeof import('./../src/components/plugin/item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../src/components/sidebar/index.vue')['default']
    SidebarItem: typeof import('./../src/components/sidebar/item.vue')['default']
    TransitionHorizontal: typeof import('./../src/components/transition/horizontal.vue')['default']
    TransitionVertical: typeof import('./../src/components/transition/vertical.vue')['default']
    WrapperModal: typeof import('./../src/components/wrapper/modal.vue')['default']
  }
}
